:numbered:
:toclevels: 4

= Asciidoctor Gradle Starter Project

== Building
The documentation is written in http://asciidoctor.org/[AsciiDoc] and built using the
http://asciidoctor.org/docs/asciidoctor-gradle-plugin/[Asciidoctor Gradle Plugin].
To generate the documentation you run the `asciidoctor` gradle task.  This generates
the HTML under `build\asciidoc` folder.

----
./gradlew asciidoctor
----
or on windows
----
gradlew.bat asciidoctor
----

== Editing
You can edit AsciiDoc files in any text editor.  Update this documentation by editing the file `src/docs/asciidoc/index.adoc`
and re-running the gradle `asciidoctor` task.  To make editing documentation more iterative, you can run the `asciidoctor`
task using https://docs.gradle.org/current/userguide/continuous_build.html[Gradle's continuous build mode] by passing a
 `-t` or `--continuous` switch on the command line.

In addition to regular text editors, there are tools that can help make editing a more WYSIWYG experience.

=== Intellij
The https://plugins.jetbrains.com/plugin/7391[AsciiDoc plugin] plugin for Intellij
allows you to preview an AsciiDoc file from within the Intellij IDE as you make changes.

=== Chrome Extension
The https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia[AsciiDoctor Live Preview]
extension allows you to open any AsciiDoctor file in Chrome and view changes being
made to it live without any need to reload or refresh.

== Documentation Examples

=== Bulleted List

[source,asciidoc]
----
* item one
* item two
* item three
----

Result:

* item one
* item two
* item three


=== Numbered List

[source,aaa]
----
. item one
. item two
. item three
----

Result:

. item one
. item two
. item three

=== Table

[source,asciidoc]
----
|===
|heading 1 | heading 1

|cell 1, row 1 | cell 2, row 1
|cell 1, row 2 | cell 2, row 2

|===
----

Result:

|===
|heading 1 | heading 1

|cell 1, row 1 | cell 2, row 1
|cell 1, row 2 | cell 2, row 2

|===

=== Source Code with Highlighting

[source,asciidoc]
----
[source,java]
 ----
 /**
  * main method
  */
 public static void main (String[] args) {
     // comment
 }
 ----
----

Result:

[source,java]
----
/**
 * main method
 */
public static void main (String[] args) {
    // comment
}
----

== Additional References
 * http://asciidoctor.org/[Asciidoctor]
 * http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[Asciidoctor Quick Reference]
 * http://asciidoctor.org/docs/asciidoctor-gradle-plugin/[Asciidoctor Gradle Plugin]
 * https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia[AsciiDoctor Live Preview Chrome Extension]
 * https://plugins.jetbrains.com/plugin/7391[AsciiDoc plugin for IntelliJ]
